project_id = "hliytlezggzryetekpvo"

[functions.ai-moderator]
verify_jwt = false

[functions.pm-monitor]
verify_jwt = false

[functions.geolocate]
verify_jwt = false

[functions.verify-captcha]
verify_jwt = false

[functions.check-rate-limit]
verify_jwt = false
