project_id = "hliytlezggzryetekpvo"

[functions.ai-moderator]
verify_jwt = false

[functions.pm-monitor]
verify_jwt = false

[functions.geolocate]
verify_jwt = false

[functions.verify-captcha]
verify_jwt = false

[functions.check-rate-limit]
verify_jwt = false

[functions.decrypt-pm]
verify_jwt = false

[functions.translate-message]
verify_jwt = false

[functions.irc-gateway]
verify_jwt = false

[functions.audit-log]
verify_jwt = false

[functions.art-curator]
verify_jwt = false

[functions.chat-bot]
verify_jwt = false

[functions.admin-reset-password]
verify_jwt = false

[functions.upload-image]
verify_jwt = false


[functions.donation-notify]
verify_jwt = false

[functions.image-to-irc]
verify_jwt = false

[functions.send-auth-email]
verify_jwt = false

[functions.send-parent-consent]
verify_jwt = false

[functions.verify-parent-consent]
verify_jwt = false

[functions.gif-search]
verify_jwt = false

[functions.oper-auth]
verify_jwt = false
